# Run-specific values
RUN_CODE:                               "01"

# Disc size calculation
DISC_SIZE_SPHERICAL_CUT_CKPC:           50.0
DISC_SIZE_ZCOORD_CUT_CKPC:              5.0
DISC_ENCLOSED_MASS_PERCENTILE:          90
VIRIAL_RADIUS_FRACTION:                 0.1
VIRIAL_RADIUS_TIME_THRESHOLD_GYR:       4.0
DISC_SIZE_SMOOTHING_WINDOW_LENGTH:      7
DISC_SIZE_SMOOTHING_POLYORDER:          1

# Visualization
SMOOTHING_WINDOW_LENGTH:                9
SMOOTHING_POLYORDER:                    1

# Preprocessing
SUBHALO_VELOCITY_DISTANCE_CKPC:         10.0
ROTATION_MATRIX_DISTANCE_CKPC:          10.0